name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy file
        run: cp ./app/build/outputs/apk/release/app-release-unsigned.apk ./maatouch

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: maatouch
          path: ./maatouch

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.event.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: maatouch
          path: ./
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto-build-${{ github.ref_name }}-${{ steps.slug.outputs.sha7 }}
          release_name: Auto build ${{ github.ref_name }} ${{ steps.slug.outputs.sha7 }}
          body: |
            This is an automatic build.
          draft: false
          prerelease: false
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./maatouch
          asset_name: maatouch
          asset_content_type: application/zip
      - name: Base64 encode
        run: base64 -i ./maatouch > ./maatouch.base64
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./maatouch.base64
          asset_name: maatouch.base64
          asset_content_type: text/plain
